name: ImpossibleChaos
version: 1.0
main: com.cloudxr.impossiblechaos.ImpossibleChaos
api-version: "1.21"

commands:
  chaos:
    description: Chaos control
    usage: /chaos <reload|toggle>
    permission: chaos.admin

permissions:
  chaos.admin:
    default: op
